apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vpromc
  namespace: default
  labels:
    app: vpromc
spec:
  selector:
    matchLabels:
      app: vpromc
  replicas: 1
  template:
    metadata:
      labels:
        app:  vpromc
    spec:
      containers:
      - name:  vpromc
        image:  memcached
        livenessProbe:
          tcpSocket:
            port: 11211
      
        ports:
        - containerPort:  11211
---
apiVersion: v1
kind: Service
metadata:
  name: vprocache01
  namespace: default
spec:
  selector:
    app: vpromc
  type: ClusterIP
  ports:
  - name: db
    protocol: TCP
    port: 11211
    targetPort: 11211
